import { sql } from "drizzle-orm";
import { integer, pgEnum, pgTable, real, text, timestamp } from "drizzle-orm/pg-core";

export const protocolEnum = pgEnum("protocol", ["raydium", "meteora"]);

export const tokens = pgTable("tokens", {
	id: text("id").primaryKey().default(sql`gen_random_uuid()`),
	name: text("name").notNull(),
	ticker: text("ticker").notNull(),
	url: text("url").notNull(),
	image: text("image").notNull(),
	twitter: text("twitter"),
	telegram: text("telegram"),
	website: text("website"),
	discord: text("discord"),
	farcaster: text("farcaster"),
	description: text("description"),
	mint: text("mint").notNull().unique(),
	creator: text("creator").notNull(),
	protocol: protocolEnum("protocol").notNull().default("raydium"),
	nftMinted: text("nft_minted"),
	lockId: text("lock_id"),
	lockedAmount: text("locked_amount"),
	lockedAt: timestamp("locked_at"),
	harvestedAt: timestamp("harvested_at"),
	status: text("status").notNull().default("active"),
	createdAt: timestamp("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
	lastUpdated: timestamp("last_updated").notNull().default(sql`CURRENT_TIMESTAMP`),
	completedAt: timestamp("completed_at"),
	withdrawnAt: timestamp("withdrawn_at"),
	migratedAt: timestamp("migrated_at"),
	marketId: text("market_id"),
	baseVault: text("base_vault"),
	quoteVault: text("quote_vault"),
	withdrawnAmount: real("withdrawn_amount"),
	reserveAmount: real("reserve_amount"),
	reserveLamport: real("reserve_lamport"),
	virtualReserves: real("virtual_reserves"),
	liquidity: real("liquidity"),
	currentPrice: real("current_price"),
	marketCapUSD: real("market_cap_usd"),
	tokenPriceUSD: real("token_price_usd"),
	solPriceUSD: real("sol_price_usd"),
	curveProgress: real("curve_progress"),
	curveLimit: real("curve_limit"),
	priceChange24h: real("price_change_24h"),
	price24hAgo: real("price_24h_ago"),
	volume24h: real("volume_24h"),
	inferenceCount: integer("inference_count"),
	lastVolumeReset: timestamp("last_volume_reset"),
	lastPriceUpdate: timestamp("last_price_update"),
	holderCount: integer("holder_count"),
	txId: text("tx_id"),
	migration: text("migration"),
	withdrawnAmounts: text("withdrawn_amounts"),
	poolInfo: text("pool_info"),
	lockLpTxId: text("lock_lp_tx_id"),
	imported: integer("imported").default(0),
	featured: integer("featured").default(0),
	verified: integer("verified").default(0),
	hidden: integer("hidden").default(0),
	is_token_2022: integer("is_token_2022").default(0),
	hide_from_featured: integer("hide_from_featured").default(0),
	tokenSupply: text("token_supply").default("1000000000000000"),
	tokenSupplyUiAmount: real("token_supply_ui_amount").default(1000000000),
	tokenDecimals: integer("token_decimals").default(6),
	lastSupplyUpdate: timestamp("last_supply_update"),
});
export type Token = typeof tokens.$inferSelect;
