// this is from the old repo {/* Malibu */}
export const ideas = [
	"famous person",
	"movie character",
	"animal",
	"food",
	"vehicle",
	"historical figure",
	"mythical creature",
	"meme",
	"internet personality",
	"brand",
	"product",
	"company",
	"plant",
	"rock",
	"gem",
	"mineral",
	"element",
	"color",
	"crypto",
	"NFT",
	"video game",
	"anime",
	"cartoon",
	"superhero",
	"villain",
	"AI",
	"robot",
	"alien",
	"conspiracy",
	"emoji",
	"social media",
	"streaming service",
	"podcast",
	"mixtape",
	"urban legend",
	"glitch",
	"hacker",
	"influencer",
	"streamer",
	"speedrun",
	"challenge",
	"cat video",
	"shitpost",
	"deepfake",
	"clickbait",
	"wojak",
	"4chan meme",
	"greentext",
	"DeFi protocol",
	"DAO",
	"cereal mascot",
	"fast food",
	"energy drink",
	"copypasta",
	"reddit thread",
	"Discord server",
	"web3 project",
	"Telegram group",
	"mobile game",
	"battle royale",
	"metaverse",
	"VR experience",
	"indie game",
	"Roblox avatar",
	"Minecraft mod",
	"4chan board",
	"airdrop",
	"stablecoin",
	"yield farm",
	"trading bot",
	"fitness trend",
	"internet challenge",
	"sports team",
	"dark web",
	"cyberpunk",
	"vaporwave",
	"synthwave",
	"lofi beats",
	"rage comic",
	"esports team",
	"meme stock",
	"crypto winter",
	"bull run",
	"play-to-earn",
	"move-to-earn",
	"dating app",
	"pissing contest",
	"content creator",
	"internet personality",
	"streamer",
	"micro influencer",
	"celebrity account",
	"parody profile",
	"stan account",
	"fandom page",
	"reaction channel",
	"commentary channel",
	"DIY creator",
	"tech reviewer",
	"unboxing specialist",
	"tutorial maker",
	"makeup artist",
	"fitness influencer",
	"food blogger",
	"travel vlogger",
	"Y2K revival",
	"cottagecore aesthetic",
	"dark academia",
	"light academia",
	"dreamcore style",
	"weirdcore art",
	"vaporwave edit",
	"synthwave soundtrack",
	"retrowave animation",
	"cyberpunk aesthetic",
	"solarpunk vision",
	"glitch art",
	"datamosh effect",
	"deepfake video",
	"AI-generated art",
	"prompt engineering",
	"style transfer",
	"keyboard smash",
	"reaction meme",
	"text abbreviation",
	"emoji combo",
	"copypasta format",
	"internet slang",
	"fandom terminology",
	"online dialect",
	"stan language",
	"Discord emoji",
	"chat spam",
	"keysmash reaction",
	"wholesome reply",
	"passive-aggressive period",
	"caps lock emphasis",
	"text formatting",
	"leetspeak revival",
	"internet acronym",
	"subreddit lore",
	"fandom shipping",
	"fan theory",
	"headcanon debate",
	"cosplay community",
	"convention meetup",
	"online roleplay",
	"virtual world",
	"MMO guild",
	"gaming clan",
	"speedrun community",
	"modding group",
	"fan fiction site",
	"wiki contributors",
	"flash mob",
	"viral challenge",
	"internet mystery",
	"mandela effect",
	"online conspiracy",
	"information bubble",
	"filter bubble",
	"viral hoax",
	"internet legend",
	"digital folklore",
	"internet linguistics",
	"social experiment",
	"internet archive",
	"wayback machine",
	"deleted video",
	"cancelled event",
	"leaked content",
	"beta feature",
	"easter egg",
	"hidden message",
	"content about content",
	"reaction to reactions",
	"commentary on commentary",
	"meta-analysis",
	"review of reviews",
	"trends about trends",
	"memes about memes",
	"parody of parodies",
	"satire of satire",
	"critique of critiques",
	"explanation of explanations",
	"guide to guides",
	"list of lists",
	"collection of collections",
	"archive of archives",
	"history of histories",
	"reference to references",
	"callback to callbacks",
	"homage to homages",
	"tribute to tributes",
];

export const adjectives = [
	"stupid",
	"low effort",
	"funny",
	"meme",
	"trending",
	"popular",
	"cool",
	"unique",
	"futuristic",
	"retro",
	"cursed",
	"blessed",
	"savage",
	"cringe",
	"based",
	"chad",
	"sus",
	"poggers",
	"viral",
	"epic",
	"yolo",
	"dank",
	"lit",
	"rekt",
	"fire",
	"goated",
	"smol",
	"vibe",
	"swag",
	"toxic",
	"derp",
	"woke",
	"thicc",
	"fried",
	"shrek",
	"giga",
	"mega",
	"ultra",
	"hyper",
	"deep",
	"glitch",
	"broken",
	"hacked",
	"jacked",
	"flex",
	"sheesh",
	"bussin",
	"clapped",
	"yeet",
	"ratio'd",
	"copypasta",
	"stonks",
	"smh",
	"fomo",
	"salty",
	"sweaty",
	"tilted",
	"pepega",
	"boomer",
	"zoomer",
	"cooked",
	"clout",
	"simp",
	"hopium",
	"copium",
	"maxi",
	"anti",
	"hodl",
	"ngmi",
	"wagmi",
	"shitcoin",
	"moonshot",
	"paperhands",
	"diamond",
	"rugpull",
	"jpegged",
	"ngl",
	"iykyk",
	"deadass",
	"galaxy",
	"himbo",
	"janky",
	"cheugy",
	"mid",
	"rent-free",
	"soy",
	"sigma",
	"unhinged",
	"frfr",
	"ong",
	"unironically",
	"normie",
	"L",
	"W",
	"catfished",
	"NPC",
	"main character",
	"doxxed",
	"pilled",
	"redpilled",
	"blackpilled",
	"doomscrolling",
	"smoothbrain",
	"degens",
	"frens",
	"whale",
	"kms",
	"gaslighting",
	"whataboutism",
	"memeable",
	"clickbaity",
	"parasocial",
	"dicks",
	"butts",
	"chronically online",
	"extremely offline",
	"touch-starved",
	"grass-touching",
	"parasocial",
	"paywalled",
	"shadowbanned",
	"algorithm-pilled",
	"mainstreamed",
	"terminally",
	"4K",
	"HD",
	"corrupted",
	"glitched",
	"deep-fried",
	"nuked",
	"distorted",
	"compressed",
	"expanded",
	"based",
	"cringe",
	"sus",
	"no cap",
	"fr fr",
	"ong",
	"lowkey",
	"highkey",
	"mid",
	"goated",
	"slept on",
	"rent free",
	"main character",
	"core memory",
	"toxic",
	"parasocial",
	"chronically online",
	"touch grass",
	"unserious",
	"slay",
	"vibe check",
	"immaculate",
	"chaotic",
	"iconic",
	"legendary",
	"chef's kiss",
	"aesthetic",
	"elite",
	"premium",
	"top tier",
	"god tier",
	"S-tier",
	"built different",
	"hits different",
	"understood the assignment",
	"moment of silence",
	"living rent-free",
	"lives in my head",
	"zero thoughts",
	"head empty",
	"sweaty",
	"try-hard",
	"casual",
	"meta",
	"nerfed",
	"buffed",
	"OP",
	"broken",
	"aimbot",
	"hacker",
	"camper",
	"griefer",
	"noob",
	"pro",
	"clutch",
	"carried",
	"boosted",
	"hard-stuck",
	"cracked",
	"washed",
	"verified",
	"mutuals",
	"moots",
	"ratio'd",
	"cancelled",
	"dragged",
	"stan",
	"bias",
	"bias wrecker",
	"ship",
	"OTP",
	"alt",
	"main",
	"burner",
	"sock",
	"private",
	"public",
	"trending",
	"unironically",
	"ironically",
	"no joke",
	"fr",
	"genuinely",
	"literally",
	"actually",
	"unseriously",
	"sarcastically",
	"jokingly",
	"affectionately",
	"platonically",
	"romantically",
	"parasocially",
	"professionally",
	"casually",
	"respectfully",
	"disrespectfully",
	"aggressively",
	"passively",
	"literally",
	"actually",
	"genuinely",
	"absolutely",
	"completely",
	"totally",
	"utterly",
	"entirely",
	"no cap",
	"deadass",
	"straight up",
	"lowkey",
	"highkey",
	"undeniably",
	"objectively",
	"aesthetic",
	"vibey",
	"fit",
	"drip",
	"clean",
	"fresh",
	"fire",
	"heat",
	"icy",
	"frosty",
	"drippy",
	"saucy",
	"bussin",
	"serving",
	"snatched",
	"on point",
	"stylish",
	"fashion",
	"bricked up",
	"decked out",
	"pov",
	"storytime",
	"photo dump",
	"spam account",
	"shitposting",
	"thread",
	"hot take",
	"unpopular opinion",
	"controversial take",
	"clickbait",
	"bait",
	"cursed",
	"blessed",
	"blursed",
	"wholesome",
	"satisfying",
	"oddly satisfying",
	"mildly infuriating",
	"deeply concerning",
	"absolutely deranged",
	"cottagecore",
	"dark academia",
	"light academia",
	"normcore",
	"y2k",
	"indie sleaze",
	"coastal grandmother",
	"barbiecore",
	"coquette",
	"balletcore",
	"fairycore",
	"dreamcore",
	"kidcore",
	"weirdcore",
	"vaporwave",
	"dreamscape",
	"liminal",
	"nostalgic",
	"stan",
	"anti",
	"mutual",
	"moot",
	"oomf",
	"moots",
	"reply guy",
	"simp",
	"stan twitter",
	"stan account",
	"fan account",
	"fan cam",
	"fan edit",
	"ship edit",
	"ship name",
	"multiship",
	"otp",
	"notp",
	"fanfiction",
	"headcanon",
	"screaming",
	"crying",
	"throwing up",
	"dying",
	"sobbing",
	"ascending",
	"transcending",
	"screeching",
	"howling",
	"cackling",
	"gasping",
	"wheezing",
	"shaking",
	"vibrating",
	"ascending to another plane",
	"losing it",
	"deceased",
	"flatlined",
	"zero thoughts",
	"brain rot",
	"chef's kiss",
	"top tier",
	"elite",
	"superior",
	"immaculate",
	"phenomenal",
	"revolutionary",
	"game-changing",
	"innovative",
	"groundbreaking",
	"iconic",
	"legendary",
	"classic",
	"timeless",
	"masterpiece",
	"work of art",
	"cultural reset",
	"cultural phenomenon",
	"cultural icon",
	"cultural landmark",
];

export const nouns = [
	"elon",
	"doge",
	"trump",
	"cat",
	"pepe",
	"wojak",
	"chad",
	"karen",
	"boomer",
	"zoomer",
	"doomer",
	"kek",
	"moon",
	"ape",
	"frog",
	"wojak",
	"chad",
	"soyjak",
	"bruh",
	"musk",
	"bezos",
	"zuck",
	"stonks",
	"tendies",
	"wagmi",
	"ngmi",
	"fomo",
	"hodl",
	"whale",
	"diamond",
	"wojak",
	"pepega",
	"pog",
	"kappa",
	"copium",
	"hopium",
	"wojak",
	"wojack",
	"nft",
	"eth",
	"btc",
	"sol",
	"defi",
	"dao",
	"gwei",
	"wei",
	"block",
	"chain",
	"mint",
	"burn",
	"pump",
	"dump",
	"rug",
	"shill",
	"shiba",
	"floki",
	"akita",
	"cat",
	"frog",
	"grumpy",
	"bored",
	"rekt",
	"monke",
	"wojak",
	"pepe",
	"dank",
	"doggo",
	"catto",
	"fishe",
	"birb",
	"snek",
	"honse",
	"shibe",
	"pupper",
	"chonker",
	"floof",
	"boi",
	"mr",
	"sus",
	"amogus",
	"imposter",
	"vibe",
	"yeet",
	"mood",
	"stan",
	"clout",
	"drip",
	"vibe",
	"fit",
	"normie",
	"anon",
	"wojie",
	"kermit",
	"gritty",
	"cheems",
	"swole",
	"buff",
	"thicc",
	"bonk",
	"horny",
	"simp",
	"incel",
	"chad",
	"stacy",
	"becky",
	"virgin",
	"sigma",
	"alpha",
	"beta",
	"gamma",
	"delta",
	"epsilon",
	"redpill",
	"blackpill",
	"bluepill",
	"pill",
	"anon",
	"sus",
	"sigma",
	"grindset",
	"mindset",
	"king",
	"queen",
	"lord",
	"gigachad",
	"genz",
	"millenial",
	"boomer",
	"doomer",
	"zoomer",
	"cooler",
	"xqc",
	"ludwig",
	"mizkif",
	"pokimane",
	"ludwig",
	"shroud",
	"ninja",
	"pawg",
	"dream",
	"corpse",
	"sykkuno",
	"hasan",
	"azan",
	"crypto",
	"vbucks",
	"robux",
	"discord",
	"nitro",
	"mod",
	"admin",
	"ban",
	"mute",
	"kick",
	"ratio",
	"cancel",
	"senpai",
	"baka",
	"uwu",
	"owo",
	"pogchamp",
	"poggers",
	"omegalul",
	"sadge",
	"copege",
	"kekw",
	"monkas",
	"pepehands",
	"pepega",
	"batchest",
	"catjam",
	"juicer",
	"himbo",
	"bimbo",
	"masc",
	"himbo",
	"daddy",
	"mommy",
	"token",
	"coin",
	"memecoin",
	"shitcoin",
	"altcoin",
	"moonshot",
	"rugpull",
	"ponzi",
	"shibarium",
	"doge",
	"safemoon",
	"luna",
	"satoshi",
	"vitalik",
	"sbf",
	"cz",
	"block",
	"hash",
	"node",
	"validator",
	"algorithm",
	"bot",
	"neural",
	"gpt",
	"llm",
	"midjourney",
	"dalle",
	"stable",
	"diffusion",
	"transformer",
	"github",
	"gitlab",
	"stack",
	"overflow",
	"hackathon",
	"leetcode",
	"bug",
	"feature",
	"update",
	"patch",
	"gamer",
	"sweat",
	"noob",
	"pro",
	"speedrunner",
	"strat",
	"meta",
	"nerf",
	"buff",
	"ban",
	"report",
	"toxic",
	"grief",
	"camp",
	"mlg",
	"comp",
	"casual",
	"ranked",
	"pubs",
	"lobby",
	"doge",
	"pepe",
	"shaw",
	"wojak",
	"cheems",
	"chad",
	"soyjak",
	"gigachad",
	"doomer",
	"consoomer",
	"npc",
	"troll",
	"stonks",
	"meme man",
	"giga",
	"sigma",
	"peepo",
	"monkas",
	"pogchamp",
	"kermit",
	"boba",
	"avocado",
	"toast",
	"matcha",
	"latte",
	"energy",
	"monster",
	"redbull",
	"gfuel",
	"dorito",
	"cheeto",
	"takis",
	"ramen",
	"sushi",
	"poke",
	"acai",
	"smoothie",
	"oat milk",
	"cold brew",
	"kombucha",
	"doggo",
	"pupper",
	"catto",
	"chonker",
	"snek",
	"birb",
	"monke",
	"capybara",
	"racoon",
	"possum",
	"axolotl",
	"frogge",
	"bunno",
	"shork",
	"duck",
	"cow",
	"goat",
	"bee",
	"panda",
	"koala",
	"drop",
	"collab",
	"shoutout",
	"tour",
	"karen",
	"kyle",
	"chad",
	"stacy",
	"becky",
	"doomer",
	"zoomer",
	"boomer",
	"millennial",
	"genz",
	"alpha",
	"sigma",
	"beta",
	"incel",
	"simp",
	"stan",
	"normie",
	"basic",
	"pick me",
	"emoji",
	"emote",
	"sticker",
	"gif",
	"filter",
	"effect",
	"preset",
	"wallpaper",
	"theme",
	"icon",
	"avatar",
	"profile",
	"banner",
	"overlay",
	"logo",
	"watermark",
	"thumbnail",
	"intro",
	"outro",
	"transition",
	"vibe",
	"mood",
	"energy",
	"aesthetic",
	"era",
	"phase",
	"moment",
	"season",
	"arc",
	"saga",
	"lore",
	"timeline",
	"multiverse",
	"dimension",
	"reality",
	"simulation",
	"experience",
	"journey",
	"quest",
	"adventure",
	"meme",
	"trend",
	"viral",
	"challenge",
	"hashtag",
	"thread",
	"forum",
	"board",
	"community",
	"fandom",
	"stan",
	"culture",
	"movement",
	"aesthetic",
	"wave",
	"core",
	"punk",
	"academia",
	"posting",
	"dumping",
	"Superfluous",
	"fun",
	"dust",
	"Free",
	"esim",
	"Money",
	"mog",
	"Rug",
	"power surge!",
	"Esophagus",
	"Horchata",
	"nothing",
	"UWU",
	"rugpull",
	"Weed",
	"Having Fun.",
	"Love",
	"quant",
	"Genesis",
	"Water",
];

export const exampleFormats = [
	`
{
  "name": "DogeBonk",
  "symbol": "BONK",
  "description": "The ultimate meme token that combines Doge with bonking powers. Send your friends to horny jail with BONK!",
  "prompt": "A Shiba Inu dog wearing a police hat and holding a bonk bat, digital art style, vibrant colors, meme aesthetic"
}
`,
	`
{
  "name": "PepeCoin",
  "symbol": "PEPE",
  "description": "The rarest Pepe of them all. Each token represents a unique piece of internet history. Feels good man.",
  "prompt": "A rare Pepe frog wearing a crown and holding a golden coin, 90s internet glitch art style, green and gold color scheme, web3 aesthetic"
}
`,
	`
{
  "name": "AmongBucks",
  "symbol": "SUS",
  "description": "The impostor is hiding in your wallet! Trade these tokens wisely or get ejected from the financial spaceship.",
  "prompt": "An Among Us character holding a bag of money with a suspicious look, digital illustration, vibrant colors, space background"
}
`,
	`
{
  "name": "CatJAM",
  "symbol": "MEOW",
  "description": "Vibing to the blockchain beat. This token pumps to the rhythm of internet culture. Headphones on, volume up!",
  "prompt": "A cool cat wearing headphones and sunglasses, nodding its head to music, neon colors, animated style, party atmosphere"
}
`,
	`
{
  "name": "MoonLambo",
  "symbol": "LAMBO",
  "description": "When moon? When Lambo? Now! This token fuels your rocket to financial freedom. Buckle up for the ride!",
  "prompt": "A Lamborghini parked on the moon with Earth in the background, crypto symbols floating around, hyperrealistic render"
}
`,
	`
{
  "name": "WojackFinance",
  "symbol": "PAIN",
  "description": "Feel the market's emotions through this token. Bull runs feel like Gigachad, bear markets feel like Doomer. Pain is temporary.",
  "prompt": "A split-face Wojak character showing 'bull market' happiness on one side and 'bear market' depression on the other, meme style"
}
`,
	`
{
  "name": "GigaChad",
  "symbol": "CHAD",
  "description": "The strongest token in your portfolio. Never skips a pump day. Flexing those gains while virgin tokens cry.",
  "prompt": "A muscular, black and white Chad figure holding heavy bags labeled 'gains', dramatic lighting, sigma male grindset aesthetic"
}
`,
	`
{
  "name": "MemeCat",
  "symbol": "LOLCAT",
  "description": "I can haz profits? This token brings back the classic internet cats that started it all. Cheezburger included.",
  "prompt": "A classic LOLcat with Impact font meme text above and below, sitting on a pile of cryptocurrency coins, vintage internet aesthetic"
}
`,
	`
{
  "name": "YEETcoin",
  "symbol": "YEET",
  "description": "Throw your investment worries away! This token yeets itself to the moon with no roadmap, no utility, just vibes.",
  "prompt": "A hand throwing a glowing coin into space, motion blur effect, bright colors, meme style with explosion effects"
}
`,
	`
{
  "name": "GlitchApi",
  "symbol": "APE",
  "description": "Return to monke with these glitched primates. Each token gives you membership to the most exclusive jungle club in crypto.",
  "prompt": "A glitched out bored ape wearing sunglasses and a crown, smoking a banana like a cigar, vaporwave colors, lofi style"
}
`,
];
