name: Hourly Warmup

on:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour
  workflow_dispatch:     # Allows manual triggering via GitHub UI

jobs:
  run-warmup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make warmup.sh executable
        run: chmod +x ./warm.sh

      - name: Run warmup.sh
        run: ./warm.sh
