name: Hourly warmup

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Make warm.sh executable
        run: chmod +x ./warm.sh

      - name: Run warm.sh
        run: ./warm.sh
